#-------------------------------
# General Site Settings
title: La foret rouge
# logo: logo.svg # You can add own logo.
description: Hello!


#-------------------------------
# Author Settings
author:
  name: Steven Shin
  image: assets/img/profile2.jpeg
  email: cheesecat47@gmail.com


#-------------------------------
# Contact links
github: https://www.github.com/cheesecat47/
instagram: https://instagram.com/__0f4c81/ # Add your Instagram handle
linkedin: http://www.linkedin.com/in/steven-shin-638413192/
envelope: mailto:cheesecat47@gmail.com


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: cheesecat47 # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
# instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
# instagram-profile: __0f4c81 # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: G-Q8FHR3Z8GL # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
